name: Deploy Next.js

on:
  push:
    branches:
      - master  # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: npm install
        
      - name: Build Next.js app
        run: npm run build
        
      - name: Deploy to Cloud Panel
        run: |
          # Example deployment script (replace with your actual deployment commands)
          'cd /htdocs/www.spoares.com/Damned && git pull origin master && npm install && npm run build && pm2 restart 0'
