name: Deploy Next.js Application

on:
  push:
    branches:
      - master # or the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: 107.174.102.231
          SSH_USER: damnedventures-new
          SSH_PORT: 22 # default SSH port, change if necessary
        run: |
          ssh -i private_key -p $SSH_PORT $SSH_USER@$SSH_HOST -t << 'EOF'
            rm -rf /home/damnedventures-new/htdocs/new.spoares.com*
          EOF
          rsync -avz -e "ssh -i private_key -p $SSH_PORT" ./ $SSH_USER@$SSH_HOST:/home/damnedventures-new/htdocs/new.spoares.com

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 107.174.102.231
          username: damnedventures-new
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            pm2 stop all
            cd /home/damnedventures-new/htdocs/new.spoares.com
            npm install
            npm run build
            pm2 start npm --name "nextjs-app" -- run start
