name: Deploy Next.js Application

on:
  push:
    branches:
      - master # or the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 107.174.102.231
          username: spoares
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            pm2 stop all
            cd /home/spoares/htdocs/www.spoares.com/Damned
            npm install
            npm run build
            pm2 start npm --name "Damned" -- run dev
