name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no spoares@107.174.102.231 << EOF
          sudo apt install nodejs
          sudo apt install npm
          cd htdocs/www.spoares.com/Damned || { echo "Directory not found"; exit 1; }
          git pull origin master
          npm install
          npm run build
          pm2 restart Damned
        EOF
